Add JS check

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -7,30 +7,6 @@ PROGRESS=
 COLORS=Y
 
 PROJECT=`php -r "echo dirname(dirname(dirname(realpath('$0'))));"`
-STAGED_FILES_CMD=`git diff-index --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`
-
-# Determine if a file list is passed
-if [ "$#" -eq 1 ]
-then
-  oIFS=$IFS
-  IFS='
-  '
-  SFILES="$1"
-  IFS=$oIFS
-fi
-SFILES=${SFILES:-$STAGED_FILES_CMD}
-
-echo "Checking PHP Lint..."
-for FILE in $SFILES
-do
-  php -l -d display_errors=0 $PROJECT/$FILE
-  if [ $? != 0 ]
-  then
-    echo "Fix the error before commit."
-    exit 1
-  fi
-  FILES="$FILES $PROJECT/$FILE"
-done
 
 if [ "$IGNORE_WARNINGS" != "" ]
 then
@@ -58,9 +34,67 @@ then
   STANDARD="$PROJECT/vendor/yiisoft/yii2-coding-standards/Yii2"
 fi
 
+# JS files
+
+STAGED_FILES_CMD=`git diff-index --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.js`
+
+# Determine if a file list is passed
+if [ "$#" -eq 1 ]
+then
+  oIFS=$IFS
+  IFS='
+  '
+  SFILES="$1"
+  IFS=$oIFS
+fi
+SFILES=${SFILES:-$STAGED_FILES_CMD}
+
+for FILE in $SFILES
+do
+  FILES="$FILES $PROJECT/$FILE"
+done
+
 if [ "$FILES" != "" ]
 then
-  echo "Running Code Sniffer..."
+  echo "Running Code Sniffer for JS..."
+  $PROJECT/vendor/bin/phpcs --standard=$STANDARD --encoding=$ENCODING $COLORS $IGNORE_WARNINGS $PROGRESS $FILES
+  if [ $? != 0 ]
+  then
+    echo "Fix the error before commit."
+    exit 1
+  fi
+fi
+
+# PHP files
+
+STAGED_FILES_CMD=`git diff-index --cached --name-only --diff-filter=ACMR HEAD | grep \\\\.php`
+
+# Determine if a file list is passed
+if [ "$#" -eq 1 ]
+then
+  oIFS=$IFS
+  IFS='
+  '
+  SFILES="$1"
+  IFS=$oIFS
+fi
+SFILES=${SFILES:-$STAGED_FILES_CMD}
+
+echo "Checking PHP Lint..."
+for FILE in $SFILES
+do
+  php -l -d display_errors=0 $PROJECT/$FILE
+  if [ $? != 0 ]
+  then
+    echo "Fix the error before commit."
+    exit 1
+  fi
+  FILES="$FILES $PROJECT/$FILE"
+done
+
+if [ "$FILES" != "" ]
+then
+  echo "Running Code Sniffer for PHP..."
   $PROJECT/vendor/bin/phpcs --standard=$STANDARD --encoding=$ENCODING $COLORS $IGNORE_WARNINGS $PROGRESS $FILES
   if [ $? != 0 ]
   then
